var moment = require('moment')
var DateRangePickerProvider = require('./providers/date-range-picker.provider.js')
var DatePickerProvider = require('./providers/date-picker.provider.js')
var DateRangePicker = require('./directives/date-range-picker/date-range-picker.directive')
var Calendar = require('./directives/calendar/calendar.directive')
var ObDateRangePicker = require('./directives/ob-date-range-picker/ob-date-range-picker.directive.js')
var ObDayPicker = require('./directives/ob-day-picker/ob-day-picker.directive')

angular.module('angularjs-daterange', [])
  .constant('moment', moment)
  .provider('dateRangePickerConf', DateRangePickerProvider)
  .provider('datePickerConf', DatePickerProvider)
  .directive('dateRangePicker', DateRangePicker)
  .directive('obDaterangepicker', ObDateRangePicker)
  .directive('calendar', Calendar)
  .directive('obDaypicker', ObDayPicker)
